name: 4. build application container
run-name: build, publish and deploy ${{ github.ref }} by ${{ github.actor }}

env:
  NODE_VERSION: 18.x
  APP_PROJECT_NAME: |
    ${{fromJSON('
      {
        "development": "gcp-wow-cart-apps-dev-28f0",
        "dory-dev": "cart-apps-dory-dev-98d6",
        "nemo-dev": "cart-apps-nemo-dev-895a",
        "test": "gcp-wow-cart-apps-test-5ec2",
        "nonprod": "gcp-wow-cart-apps-nonprod-66ca"
      }')[inputs.ENVIRONMENT]}}
  APP_PROJECT_ID: |
    ${{fromJSON('
      {
        "development": "699012770206",
        "dory-dev": "290901608746",
        "nemo-dev": "90520429778",
        "test": "743343070162",
        "nonprod": "201908505250"
      }')[inputs.ENVIRONMENT]}}

on:
  workflow_dispatch:
    inputs:
      PUSH_IMAGE:
        type: choice
        description: "Push image to GCR?"
        required: true
        options:
          - "yes"
          - "no"
  workflow_call:
    inputs:
      PUSH_IMAGE:
        type: string
        description: "Push image to GCR?"
        required: true
        default: "no"
    outputs:
      image_tag:
        description: "The published docker image tag"
        value: ${{ jobs.build_and_publish_container.outputs.image_tag }}

jobs:
  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint test

  build_and_publish_container:
    name: Build App
    needs: [lint]
    uses: cartologyau/srops-github-workflows/.github/workflows/build-image.yml@main
    secrets: inherit
    with:
      deployment_branch: ${{ github.ref }}
      build_file: ./apps/peng-self-service-portal/build/build.sh
      docker_file: ./apps/peng-self-service-portal/build/Dockerfile # note this is used purely for the dockerfile lint step
      gcr: gcr.io/gcp-wow-cart-srops-shared-0aa0/peng-adplatform-web-portal
      gcr_prod: gcr.io/gcp-wow-cart-srops-prod-b660/peng-adplatform-web-portal
      srops_service_account: "project-service-account@gcp-wow-cart-srops-shared-0aa0.iam.gserviceaccount.com"
      srops_identity_provider: "projects/506813995039/locations/global/workloadIdentityPools/workload-identity-pool/providers/github-actions-provider"
      srops_prod_service_account: "project-service-account@gcp-wow-cart-srops-prod-b660.iam.gserviceaccount.com"
      srops_prod_identity_provider: "projects/426346946201/locations/global/workloadIdentityPools/workload-identity-pool/providers/github-actions-provider"
      push_image_gcr: ${{ inputs.PUSH_IMAGE == 'yes'}}
