name: 3. development branch build
run-name: development branch build ${{ github.ref }} by ${{ github.actor }}

on:
  push:
    branches-ignore:
      - main

jobs:
  run-development:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      PUSH_IMAGE: "yes"

  update-argocd-dev:
    needs: [run-development]
    uses: cartologyau/srops-github-workflows/.github/workflows/deploy-gitops-tag.yml@main
    secrets: inherit
    with:
      gitops-repo: peng-gitops
      target-file: services/adplatform-web-portal/values-dev.yaml
      docker-image-tag: ${{ needs.run-development.outputs.image_tag }}
