name: 2. main branch build
run-name: main branch build ${{ github.ref }} by ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  pathcheck:
    runs-on: ubuntu-latest
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
      apps: ${{ steps.filter.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Path-check
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            terraform:
              - 'terraform/**'
            apps:
              - 'apps/**'

  build-application:
    needs: [pathcheck]
    if: ${{ needs.pathcheck.outputs.apps == 'true' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      PUSH_IMAGE: "yes"

  tf-dev:
    needs: [pathcheck]
    if: ${{ needs.pathcheck.outputs.terraform == 'true' }}
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      ENVIRONMENT: "development"
      DRY_RUN: ${{ github.event_name == 'push' && 'no' || 'yes' }}
      RUN_VALIDATE: "yes"

  tf-dev-alpha:
    needs: [tf-dev]
    if: ${{ needs.pathcheck.outputs.terraform == 'true' }}
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      ENVIRONMENT: "development"
      DRY_RUN: ${{ github.event_name == 'push' && 'no' || 'yes' }}
      RUN_VALIDATE: "yes"
      ENV_SUFFIX: "-alpha"

  tf-dory:
    needs: [pathcheck]
    if: ${{ needs.pathcheck.outputs.terraform == 'true' }}
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      ENVIRONMENT: "dory-dev"
      DRY_RUN: ${{ github.event_name == 'push' && 'no' || 'yes' }}
      RUN_VALIDATE: "yes"
  tf-nemo:
    needs: [pathcheck]
    if: ${{ needs.pathcheck.outputs.terraform == 'true' }}
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      ENVIRONMENT: "nemo-dev"
      DRY_RUN: ${{ github.event_name == 'push' && 'no' || 'yes' }}
      RUN_VALIDATE: "yes"

  tf-test:
    needs: [tf-dev]
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      ENVIRONMENT: "test"
      DRY_RUN: ${{ github.event_name == 'push' && 'no' || 'yes' }}
      RUN_VALIDATE: "no"

  tf-test-alpha:
    needs: [tf-test]
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      ENVIRONMENT: "test"
      DRY_RUN: ${{ github.event_name == 'push' && 'no' || 'yes' }}
      RUN_VALIDATE: "no"
      ENV_SUFFIX: "-alpha"

  tf-nonprod:
    needs: [tf-test]
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      ENVIRONMENT: "nonprod"
      DRY_RUN: ${{ github.event_name == 'push' && 'no' || 'yes' }}
      RUN_VALIDATE: "no"

  tf-production:
    needs: [tf-nonprod]
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      ENVIRONMENT: "production"
      DRY_RUN: ${{ github.event_name == 'push' && 'no' || 'yes' }}
      RUN_VALIDATE: "no"
