name: 1. tag build
run-name: tag build ${{ github.ref }} by ${{ github.actor }}

on:
  push:
    tags:
      - v**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      PUSH_IMAGE: "yes"
